pdf:
	Rscript -e "rmarkdown::render('example.Rmd', 'pdf_document')"

html:
	Rscript -e "rmarkdown::render('example.Rmd', 'html_document')"

beamer:
	Rscript -e "rmarkdown::render('example.Rmd', 'beamer_presentation')"


